import { GeistMono } from "geist/font/mono";
import "./app.css";
import { ThemeProvider } from "next-themes";
import Header from "../components/header";
import Footer from "../components/footer";

export const metadata = {
  title: "Lexington NextJS Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider defaultTheme="cyberpunk">
        <body className={GeistMono.className}>
          <Header />
          <main className="mx-auto p-8">{children}</main>
          <Footer />
        </body>
      </ThemeProvider>
    </html>
  );
}
